### PR TITLE
more license info

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by ocefpaf** [comment]
I guess that this error is due to the new conda-build and other conda related dependencies we updated these past few days :-/

```
anaconda_upload is not set.  Not uploading wheels: []
+ upload_or_check_non_existence /recipe_root conda-forge --channel=main
Traceback (most recent call last):
  File "/opt/conda/bin/upload_or_check_non_existence", line 13, in <module>
    from binstar_client.utils import get_binstar
ImportError: cannot import name 'get_binstar'
+ exit 1
Exited with code 1
```

**Comment by jakirkham** [comment]
Just updated `anaconda-client` today, wouldn't be surprised if that is the cause. That said, it was just a few patch release above what we last had. So would have hoped there wouldn't be a break like this. Happy to pull it until we get tooling sorted.

**Comment by jakirkham** [comment]
Moved the latest build to a label called `hold`. Feel free to restart CI. Expect the issue should go away. Will have to figure out whether we raise upstream or fix the upload script.

**Comment by jakirkham** [comment]
Raised upstream as issue ( https://github.com/Anaconda-Platform/anaconda-client/issues/463 ) for now.

**Pull request merged**
