### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jjhelmus**
Also removed use of autoreconf in build as this should not, as least as far as I can tell, be needed.

### CODE REVIEW

**Comment by ocefpaf** [comment]
OS X is not happy :unamused: 

```shell
libtool: link: gcc -dynamiclib  -o .libs/libfl.2.dylib  .libs/libmain.o .libs/libyywrap.o   -lm  -arch x86_64 -arch x86_64   -install_name  /Users/travis/miniconda3/conda-bld/recipe_1481039128619/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libfl.2.dylib -compatibility_version 3 -current_version 3.0 -Wl,-single_module
Undefined symbols for architecture x86_64:
  "_yylex", referenced from:
      _main in libmain.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jjhelmus** [comment]
Looks like an update to 2.6.0+ might be required, https://sourceforge.net/p/flex/bugs/182/

**Comment by jjhelmus** [comment]
Or more precisely the `Makefile.am` patch is not applied to the Makefile if `autoconf` is not run, hence the failure.  So either `autoconf` must be run or we need to update to a newer version.  I vote for the later.

**Comment by ocefpaf** [comment]
>  I vote for the later.

:+1: it seems that there is a PR for that in #4

**Comment by jjhelmus** [comment]
Update to version `2.6.2` and applied the suggested yum install for bison in PR #8

**Comment by jjhelmus** [comment]
Closing in favor of #9

**Pull request closed without merging**
